import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import { join } from "path";
import { guardPrivateRead } from "@/lib/server/protected-mutation";

// Never let Next statically optimize/cache this route — catalyst_report.json
// is regenerated by the catalyst-layer cron and every request must read the
// current file (mirrors the trades route's no-store semantics).
export const dynamic = "force-dynamic";

const DATA_PATH = join(
  process.env.HOME || "/Users/admin",
  ".openclaw/workspace/shared/artifacts/quantitative/catalyst_report.json"
);

function isValidPayload(data: unknown): data is { generated: unknown } {
  if (!data || typeof data !== "object") return false;
  const d = data as { generated?: unknown };
  return typeof d.generated !== "undefined";
}

export async function GET(req: Request) {
  const p03Guard = await guardPrivateRead(req);
  if (!p03Guard.ok) return p03Guard.response;
  try {
    const raw = await readFile(DATA_PATH, "utf-8");
    const data = JSON.parse(raw) as unknown;
    if (isValidPayload(data)) {
      return NextResponse.json(data, {
        headers: { "Cache-Control": "no-store", "X-CC-Catalyst-Source": "fs" },
      });
    }
  } catch {
    /* fall through to unavailable */
  }

  return NextResponse.json(
    {
      unavailable: true,
      message:
        "Catalyst report not on this host yet. Sync `catalyst_report.json` via bridge or open Finance HQ from the machine that runs the catalyst-layer pipeline.",
    },
    {
      status: 200,
      headers: { "Cache-Control": "no-store", "X-CC-Catalyst-Source": "unavailable" },
    }
  );
}
