import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import { join } from "path";
import { guardPrivateRead } from "@/lib/server/protected-mutation";

// Never let Next statically optimize/cache this route — strategy_lab_report.json
// is regenerated by the strategy-lab cron and every request must read the
// current file (mirrors the trades route's no-store semantics).
export const dynamic = "force-dynamic";

const DATA_PATH = join(
  process.env.HOME || "/Users/admin",
  ".openclaw/workspace/shared/artifacts/quantitative/strategy_lab_report.json"
);

function isValidPayload(data: unknown): data is { verdict: unknown } {
  if (!data || typeof data !== "object") return false;
  const d = data as { verdict?: unknown };
  return typeof d.verdict !== "undefined";
}

export async function GET(req: Request) {
  const p03Guard = await guardPrivateRead(req);
  if (!p03Guard.ok) return p03Guard.response;
  try {
    const raw = await readFile(DATA_PATH, "utf-8");
    const data = JSON.parse(raw) as unknown;
    if (isValidPayload(data)) {
      return NextResponse.json(data, {
        headers: { "Cache-Control": "no-store", "X-CC-StrategyLab-Source": "fs" },
      });
    }
  } catch {
    /* fall through to unavailable */
  }

  return NextResponse.json(
    {
      unavailable: true,
      message:
        "Strategy Lab report not on this host yet. The lab cron may still be generating `strategy_lab_report.json` — check back shortly.",
    },
    {
      status: 200,
      headers: { "Cache-Control": "no-store", "X-CC-StrategyLab-Source": "unavailable" },
    }
  );
}
