-- P06 Packet 3: execution_events, model_pricing and a read-time shadow-cost view.
--
-- NOT APPLIED ANYWHERE. Do not run `supabase db push`, a schema diff or a migration repair against the
-- remote project: the P05-B3 migration was applied through execute_sql and its migration-history row is
-- missing, so those commands would misreport or try to reapply B3. Apply this file only through the reviewed
-- manual path (explicit approval, hash-checked SQL, rollback ready). Exact rollback:
-- supabase/rollbacks/20260930000000_execution_events.rollback.sql
--
-- Enforcement: the constraints below are the database's last line of defense for the truth rules that CAN be
-- expressed as row checks (usage provenance vs numbers, no total or zero counts for claude-max, no direct cost for
-- subscription or local usage, OpenClaw model unknown, typed UUID correlation, billing mode vs provider). Rules
-- that cannot be (requested model never replaced by the reported one, no derived totals for other providers,
-- no secrets in rows) are enforced by the writer and its tests, not here.
--
-- Access: RLS enabled and NO policies; anon/authenticated are revoked. Only the service role (which
-- bypasses RLS) can read or write. Rows hold metadata only: never prompts, responses, credentials,
-- authorization headers or upstream error bodies.

-- ─── execution_events ────────────────────────────────────────────────────────
create table if not exists public.execution_events (
  -- Generated by the app BEFORE persistence. It is the idempotency key: a second insert of the same id
  -- (upsert ... ignore duplicates) can never create a second event.
  id               uuid primary key,
  started_at       timestamptz not null,
  latency_ms       integer check (latency_ms is null or latency_ms >= 0),
  provider         text not null
                   check (provider in ('claude-max', 'lm-studio', 'openclaw', 'gemini', 'deepseek', 'openrouter')),
  -- The exact model the app asked for. NULL when it did not pin one (LM Studio, OpenClaw).
  model_requested  text,
  -- The model string the provider reported, verbatim. The Claude Max proxy reports a normalized FAMILY label
  -- (claude-opus-4 / claude-sonnet-4 / claude-haiku-4) and defaults it when the CLI gave none, so this is a
  -- hint, never an identity. It must not replace model_requested.
  model_reported   text,
  agent_id         text,
  purpose          text not null
                   check (purpose in (
                     'agent-reply', 'strict-delegation-rewrite', 'synthesis', 'critique', 'refine',
                     'chat-stream', 'approve-execution', 'voice', 'daily-verse', 'job', 'lead-gen'
                   )),
  outcome          text not null check (outcome in ('ok', 'empty', 'error')),
  error_class      text check (error_class in ('http', 'timeout', 'exception', 'gateway')),
  http_status      integer check (http_status is null or http_status between 100 and 599),
  -- Provider-supplied token counts only, each independently nullable. NULL means unknown, never zero.
  input_tokens     integer check (input_tokens is null or input_tokens >= 0),
  output_tokens    integer check (output_tokens is null or output_tokens >= 0),
  total_tokens     integer check (total_tokens is null or total_tokens >= 0),
  usage_quality    text not null
                   check (usage_quality in ('provider_reported', 'partial', 'ambiguous_proxy_zero', 'not_reported')),
  -- Actual/direct spend. NULL means unknown. Claude Max is a subscription and LM Studio is local: neither
  -- has a per-call cost, and this table refuses to record one (see constraints below).
  direct_cost_usd  numeric(14, 8) check (direct_cost_usd is null or direct_cost_usd >= 0),
  billing_mode     text not null check (billing_mode in ('subscription', 'local', 'unknown')),
  correlation_type text check (correlation_type in ('chat_message', 'job', 'lead')),
  correlation_id   text,
  -- Reserved for the Mission packet. Always NULL until then.
  mission_id       uuid,
  metadata         jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at       timestamptz not null default now(),

  -- An error outcome carries an error class, and only an error outcome does.
  constraint execution_events_error_class_matches_outcome
    check ((outcome = 'error') = (error_class is not null)),
  constraint execution_events_http_status_needs_http_error
    check (http_status is null or error_class = 'http'),
  -- A correlation is a typed pair: never an untyped opaque id, never a type without an id.
  constraint execution_events_correlation_is_a_pair
    check ((correlation_type is null) = (correlation_id is null)),
  -- Chat message, job and lead ids are all UUIDs; anything else is rejected rather than stored as an opaque string.
  constraint execution_events_correlation_id_is_uuid
    check (correlation_id is null
           or correlation_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  -- Usage provenance must agree with the numbers.
  constraint execution_events_usage_quality_matches_tokens
    check (
      (usage_quality = 'provider_reported'
         and input_tokens is not null and output_tokens is not null and total_tokens is not null)
      or (usage_quality = 'partial'
         and (input_tokens is not null or output_tokens is not null or total_tokens is not null)
         and (input_tokens is null or output_tokens is null or total_tokens is null))
      or (usage_quality in ('ambiguous_proxy_zero', 'not_reported')
         and input_tokens is null and output_tokens is null and total_tokens is null)
    ),
  -- The Claude Max proxy fabricates 0 for a missing count and synthesizes the total, so this table refuses to hold
  -- either as a measurement: no total, and no zero input/output, ever, for claude-max.
  constraint execution_events_claude_max_untrusted_counts
    check (
      provider <> 'claude-max'
      or (total_tokens is null
          and (input_tokens is null or input_tokens > 0)
          and (output_tokens is null or output_tokens > 0))
    ),
  -- Independent of the rule above: a Claude Max row is never "provider_reported", and an all-zero (or empty) Claude Max
  -- count shape can only be labelled unknown, so no zero can be read, or priced, as a measurement.
  constraint execution_events_claude_max_zero_is_unknown
    check (
      provider <> 'claude-max'
      or usage_quality in ('ambiguous_proxy_zero', 'not_reported')
      or (usage_quality = 'partial' and coalesce(input_tokens, 0) + coalesce(output_tokens, 0) > 0)
    ),
  -- A proxy zero is only ever an "ambiguous_proxy_zero" and only from the Claude Max proxy.
  constraint execution_events_proxy_zero_is_claude_max_only
    check (usage_quality <> 'ambiguous_proxy_zero' or provider = 'claude-max'),
  constraint execution_events_billing_mode_matches_provider
    check (
      (provider = 'claude-max') = (billing_mode = 'subscription')
      and (provider = 'lm-studio') = (billing_mode = 'local')
    ),
  -- Never translate subscription or local usage into fake marginal spend.
  constraint execution_events_no_direct_cost_for_subscription_or_local
    check (direct_cost_usd is null or provider not in ('claude-max', 'lm-studio')),
  -- The model behind OpenClaw is configured outside this repo and stays unknown.
  constraint execution_events_openclaw_model_unknown
    check (provider <> 'openclaw' or (model_requested is null and model_reported is null))
);

create index if not exists execution_events_started_at_idx
  on public.execution_events (started_at desc);
create index if not exists execution_events_correlation_idx
  on public.execution_events (correlation_type, correlation_id)
  where correlation_id is not null;

alter table public.execution_events enable row level security;
revoke all on table public.execution_events from anon, authenticated;

-- ─── model_pricing (reference data with provenance) ──────────────────────────
create table if not exists public.model_pricing (
  id                          uuid primary key default gen_random_uuid(),
  provider                    text not null,
  model                       text not null,
  input_usd_per_mtok          numeric(12, 6) not null check (input_usd_per_mtok >= 0),
  output_usd_per_mtok         numeric(12, 6) not null check (output_usd_per_mtok >= 0),
  cache_read_usd_per_mtok     numeric(12, 6) check (cache_read_usd_per_mtok is null or cache_read_usd_per_mtok >= 0),
  cache_write_5m_usd_per_mtok numeric(12, 6) check (cache_write_5m_usd_per_mtok is null or cache_write_5m_usd_per_mtok >= 0),
  cache_write_1h_usd_per_mtok numeric(12, 6) check (cache_write_1h_usd_per_mtok is null or cache_write_1h_usd_per_mtok >= 0),
  -- Provenance is mandatory: a price with no source cannot exist, so no shadow cost can rest on one.
  source_url                  text not null check (length(btrim(source_url)) > 0),
  retrieved_on                date not null,
  effective_from              date,
  notes                       text,
  unique (provider, model, retrieved_on)
);

alter table public.model_pricing enable row level security;
revoke all on table public.model_pricing from anon, authenticated;

-- Point-in-time semantics: a row applies to an event from coalesce(effective_from, retrieved_on) onward (UTC date of
-- the event's started_at). effective_from is the date a price took effect when known; when it is not known, the
-- earliest date we can vouch for is retrieved_on. An event that predates every row for its model has NO price, so
-- its shadow cost is unknown (not the latest price, not zero). Adding a later row never changes earlier events.
--
-- The three Anthropic models verified on 2026-09-30 against Anthropic's official price list. Rates are
-- USD per million tokens (standard, global, non-batch). Cache read is 0.1x input; 5m write 1.25x; 1h write 2x.
-- The mapping from the page's display names ("Claude Opus 4.6") to the app's model ids ("claude-opus-4-6")
-- is by naming convention. effective_from is unknown, so it is left NULL.
insert into public.model_pricing
  (provider, model, input_usd_per_mtok, output_usd_per_mtok, cache_read_usd_per_mtok,
   cache_write_5m_usd_per_mtok, cache_write_1h_usd_per_mtok, source_url, retrieved_on, notes)
values
  ('anthropic', 'claude-opus-4-6',   5.000000, 25.000000, 0.500000, 6.250000, 10.000000,
   'https://platform.claude.com/docs/en/about-claude/pricing', date '2026-09-30',
   'Claude Opus 4.6, list price. Sonnet 4.6 and earlier use the previous tokenizer.'),
  ('anthropic', 'claude-sonnet-4-6', 3.000000, 15.000000, 0.300000, 3.750000,  6.000000,
   'https://platform.claude.com/docs/en/about-claude/pricing', date '2026-09-30',
   'Claude Sonnet 4.6, list price.'),
  ('anthropic', 'claude-haiku-4-5',  1.000000,  5.000000, 0.100000, 1.250000,  2.000000,
   'https://platform.claude.com/docs/en/about-claude/pricing', date '2026-09-30',
   'Claude Haiku 4.5, list price.')
on conflict (provider, model, retrieved_on) do nothing;

-- ─── shadow cost (list-price EQUIVALENT, computed at read time, never stored) ─
-- Pricing is looked up as of the event: the row with the greatest coalesce(effective_from, retrieved_on) that is on
-- or before the event's UTC start date. Ties are broken by the later retrieved_on; unique (provider, model,
-- retrieved_on) makes retrieved_on distinct per model, so the order is total and the choice deterministic.
--
-- This is NOT actual spend. Claude Max is a subscription; direct_cost_usd stays NULL. The figure answers
-- "what would these tokens cost at API list price", and it is a LOWER BOUND: the Claude Max proxy drops
-- cache-token counts, so cache reads and writes are not included. It is only produced when ALL hold:
--   * provider is claude-max and the call succeeded with text;
--   * input and output tokens are both present and the usage is not an ambiguous proxy zero;
--   * an exact-model pricing row with a source and retrieval date exists for model_requested.
-- Anything else yields NULL, which means "unknown", not zero. security_invoker keeps RLS in force.
create or replace view public.execution_events_with_shadow_cost
with (security_invoker = true) as
select
  e.*,
  case
    when e.provider = 'claude-max'
     and e.outcome = 'ok'
     and e.usage_quality in ('provider_reported', 'partial')
     and e.input_tokens is not null
     and e.output_tokens is not null
     and p.id is not null
    then round(
           (e.input_tokens::numeric * p.input_usd_per_mtok
            + e.output_tokens::numeric * p.output_usd_per_mtok) / 1000000,
           8)
  end as shadow_cost_usd,
  case
    when e.provider = 'claude-max'
     and e.outcome = 'ok'
     and e.usage_quality in ('provider_reported', 'partial')
     and e.input_tokens is not null
     and e.output_tokens is not null
     and p.id is not null
    then 'list_price_equivalent_lower_bound_excludes_cache_tokens'
  end as shadow_cost_basis,
  p.source_url as shadow_pricing_source_url,
  p.retrieved_on as shadow_pricing_retrieved_on
from public.execution_events e
left join lateral (
  select mp.*
  from public.model_pricing mp
  where mp.provider = 'anthropic'
    and mp.model = e.model_requested
    and coalesce(mp.effective_from, mp.retrieved_on) <= (e.started_at at time zone 'UTC')::date
  order by coalesce(mp.effective_from, mp.retrieved_on) desc, mp.retrieved_on desc
  limit 1
) p on true;

revoke all on table public.execution_events_with_shadow_cost from anon, authenticated;
